# Generated by Django 5.2.1 on 2025-05-30 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Promoção')),
                ('imagem', models.ImageField(upload_to='promocoes/', verbose_name='Imagem da Promoção')),
                ('descricao_curta', models.CharField(max_length=255, verbose_name='Descrição Curta')),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Voucher')),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome')),
                ('nome_completo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome completo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('seu_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Seu Email')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Selecione uma data')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.voucher', verbose_name='Selecione seu Voucher')),
            ],
        ),
    ]
