# Generated by Django 5.2.1 on 2025-05-30 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doutoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Voucher')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoPromocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_antes', models.ImageField(blank=True, null=True, upload_to='antes_do_processo/', verbose_name='Imagem antes do processo')),
                ('imagem_depois', models.ImageField(blank=True, null=True, upload_to='resultados/', verbose_name='Imagem do Resultado')),
                ('assunto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Voucher')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição Detalhada')),
                ('data_da_publicacao', models.DateTimeField(auto_now=True, null=True)),
                ('doutora_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.doutoras', verbose_name='Selecione seu Voucher')),
            ],
        ),
    ]
