# Generated by Django 5.2.1 on 2025-05-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_doutoras_resultadopromocao'),
    ]

    operations = [
        migrations.AddField(
            model_name='doutoras',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='promocoes/', verbose_name='Imagem da Promoção'),
        ),
    ]
