# Generated by Django 5.2.1 on 2025-05-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_doutoras_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocao',
            name='disponivel',
            field=models.BooleanField(blank=True, choices=[(True, 'Sim'), (False, 'Não')], default=True, null=True),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='descricao_curta',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição Curta'),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='promocoes/', verbose_name='Imagem da Promoção'),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da Promoção'),
        ),
    ]
