# Generated by Django 5.2.1 on 2025-05-30 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_promocao_disponivel_alter_promocao_descricao_curta_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResultadoPromocao',
            new_name='Resultados',
        ),
    ]
