# Generated by Django 5.2.1 on 2025-05-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_resultadopromocao_resultados'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultados',
            name='mostra',
            field=models.BooleanField(blank=True, choices=[(True, 'Sim'), (False, 'Não')], default=True, null=True),
        ),
    ]
