# Generated by Django 5.2.1 on 2025-05-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_resultados_mostra'),
    ]

    operations = [
        migrations.AddField(
            model_name='doutoras',
            name='descricao_curricular',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Voucher'),
        ),
        migrations.AlterField(
            model_name='resultados',
            name='assunto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Assunto'),
        ),
    ]
