# Generated by Django 5.2.1 on 2025-05-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_doutoras_descricao_curricular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doutoras',
            name='descricao_curricular',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='escricao curricular do profissional'),
        ),
    ]
