# Generated by Django 5.2.3 on 2025-06-11 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_doutoras_descricao_curricular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='phone',
        ),
        migrations.AlterField(
            model_name='doutoras',
            name='descricao_curricular',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Descricao curricular do profissional'),
        ),
        migrations.AlterField(
            model_name='doutoras',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome da Doutora'),
        ),
        migrations.AlterField(
            model_name='resultados',
            name='doutora_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.doutoras', verbose_name='Doutora Responsável'),
        ),
    ]
