# Generated by Django 5.2.3 on 2025-06-11 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_agendamento_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.AlterModelOptions(
            name='doutoras',
            options={'verbose_name': 'Doutora', 'verbose_name_plural': 'Doutoras'},
        ),
        migrations.AlterModelOptions(
            name='promocao',
            options={'verbose_name': 'Promoção', 'verbose_name_plural': 'Promoções'},
        ),
        migrations.AlterModelOptions(
            name='resultados',
            options={'verbose_name': 'Resultado', 'verbose_name_plural': 'Resultados'},
        ),
        migrations.AlterModelOptions(
            name='voucher',
            options={'verbose_name': 'Voucher', 'verbose_name_plural': 'Vouchers'},
        ),
    ]
