# Generated by Django 5.2.1 on 2025-07-11 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_agendamento_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.BooleanField(blank=True, choices=[(True, 'Atendido'), (False, 'Não Atendido')], default=False, null=True),
        ),
    ]
