# Generated by Django 5.2.1 on 2025-07-11 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_agendamento_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='nome',
        ),
    ]
