#!/bin/bash
echo "Criando diretorio stitch_resources..."
mkdir -p stitch_resources

echo "Baixando Design System..."
curl -L -o stitch_resources/design_system.webp "https://lh3.googleusercontent.com/aida/AP1WRLu7F6zNs4uiWDzEvruKAx9ksIlBKPqZKNIYH7S-sdm2-Nr7BAcEVzPb9JSfLS2FuVbrsfmbOEtP4egpCRvTabMxCke4ixWKW2w9uSNNIwyaQfiY8oemxqVR8ZC45zUbrSXNixdnfg1GJUvpeVqFoP0MQzGb_fP7okXO4X6FdO5JMLx2eEqdRYRnFItKWxN_teMAh6CJ5mctwOu_58HXoFj2Rmgmiq-RycuRBrIPO1knBQ1886Q0oPTEMA"

echo "Baixando Pagina Inicial..."
curl -L -o stitch_resources/pagina_inicial.html "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ6Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpZCiVodG1sXzNmNzViODEwYTdhOTQ0ZmQ5MTkxY2I3NGYwZjhiZTJmEgoSBhCUn9GZMRgBkgEjCgpwcm9qZWN0X2lkEhVCEzk2Mjk1ODY3OTQ4MDI1ODkyMjU&filename=&opi=89354086"
curl -L -o stitch_resources/pagina_inicial.webp "https://lh3.googleusercontent.com/aida/AP1WRLvzpMQjyD5Sr3KGB2wUFD1zQKsIP-y4mk5hSc8ufrdBji6iii6j4bYnw-oY-FvoESICiyF5dcY6l9F51tAKTRLm2bszZdDsyCLicfv_OIrvAzlbd_LP4au8EHArkLJ_iTNvClUoUytBgA5YhFX81VRiV3VWFXHTl2MNouVj0E7wBRRtFSlEQh6bH9A8nXZg1mSNNT4q9cpoA-DyE6uCca3oiuMF3LkT9B6onbMNjREqjxtLmPe_r1CV"

echo "Baixando Tratamentos..."
curl -L -o stitch_resources/tratamentos.html "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ6Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpZCiVodG1sX2JjN2MyM2VkNmFiNDRmNWU4MGZkNDAwMTlmZjY0ZjAxEgoSBhCUn9GZMRgBkgEjCgpwcm9qZWN0X2lkEhVCEzk2Mjk1ODY3OTQ4MDI1ODkyMjU&filename=&opi=89354086"
curl -L -o stitch_resources/tratamentos.webp "https://lh3.googleusercontent.com/aida/AP1WRLv_SJR9I26wSjBQIPomdX2EbcfLzEP5ODReBhtCjXmwma6w4f3by4uOSJy8cHhEzjmRr8VzoI36HHhhZhaoPPyRen76f7Ewp7Naq_fw4L6nd4NvqOqNF4hb-7FwyJPqVyCiPdQFtsk-wK10UXwbxrPRkdSfUpOy7Y2Zn5YdFK8k9ubdTYv7pBjYNVyoR9Ocg4btKsUq7RjOxKawKmqGrkJuB-ppWIYBNqHV2bL4oSwgwS3kd_Dj8EaF7g"

echo "Baixando Equipe e Localizacao..."
curl -L -o stitch_resources/equipe_localizacao.html "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ6Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpZCiVodG1sX2RkMzhmMGFiOTI3OTQ1ZGNhMjMyYzcyOGMwOTgzNmViEgoSBhCUn9GZMRgBkgEjCgpwcm9qZWN0X2lkEhVCEzk2Mjk1ODY3OTQ4MDI1ODkyMjU&filename=&opi=89354086"
curl -L -o stitch_resources/equipe_localizacao.webp "https://lh3.googleusercontent.com/aida/AP1WRLvVkiJSPtf7YS5yXz8ZEpYEbO41PkqsKQqYjKBJlwd2mNXw5ZdQ7fS-k3V74Zosa6x2eoCp9jRv1PQTBtfUUsTV-AJpmc3FV313WjvLR66XM-AcYZXjwBHNH2DLpZCIvYhDfSMciYit-UF4WVb0vT6JuLGh-CYLovNCl4m5pavCtEwiuTIDashSOjhJk937KJ5Q9Mp4i9lhT3svAdws4h2nDfwU-DPGB45XioH6dKIbSKuvaryosToSEA"

echo "Concluido!"
